version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3.8.10-beta.1-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER= semarslan
      - RABBITMQ_DEFAULT_PASS= semarslan